### ISSUE TITLE
Charts get replaced with error messages when adding/removing tiers

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/rate-comparison#13]
When adding/removing a new tier, there will be a few seconds when the number of rows in the "Tier Start" box is not the same as the number of rows in the "Tier Prices" box. During this time, the charts are all replaced with a red error message. It would be nice if this error message did not appear, or if it took longer to appear, giving the user more time to adjust the tiers.

Options for fixing as I see it:

1. I tried adding an "Update Tiers" button that was tied to only the tiers and nothing else. I think the code is still present, just commented out. This sort of worked, but prevented any of the charts from appearing initially until the "update tiers" button was pressed. It would be better if the charts appeared by default, and then any subsequent changes to the tiers required a push of the "update tiers" button.

2. It is possible that each tier could have it's own row, such that the tier start and price for a tier were both int he same box, and new boxes could be added as desired? This seems like it would be a little messier and it would also require rewriting the code that reads and parses the boxes.

Other ideas are welcome.

**Comment by monobina** [comment]
Did you try using the html tag for hiding the error?

  tags$style(type="text/css",
                 ".shiny-output-error { visibility: hidden; }",
                 ".shiny-output-error:before { visibility: hidden; }"
      )

**Comment by christophertull** [comment]
No I never thought of that. Seems like a good option to try out!

**Comment by monobina** [comment]
@christophertull i used this in my apps for hiding errors that popped up while choosing between variables. I placed the code in ui and it helped hide the errors.

**Comment by christophertull** [comment]
I like what you did to suppress the errors, so I think unless you have some other trick you want to try we can just accept that the charts will disappear for a moment and we can merge to master? 

We can always open a new issue later if we think the disappearing charts are really that bad.

**Comment by monobina** [comment]
ok sounds good. i.m working on the customer classes item now. plan on getting back to this after that.

**Comment by christophertull** [comment]
Closed by f8c0fed15420888db39c5acd87043c4f4f3e2315
