### ISSUE TITLE
Multiple customer classes

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/rate-comparison#3]
Add new tabs corresponding to different customer classes.

**Comment by patwater** [comment]
@monobina how's this coming?  Need anything from me or @christophertull ?

**Comment by monobina** [comment]
@patwater @christophertull working on it currently. created an input in the ui for couple customer classes and added a data filter in the server based on those inputs. Testing to see how it goes. Will expand it to more customer classes if the testing goes fine. Will  commit my code by the end of the day tomorrow with whatever I have till then. sounds ok?

**Comment by christophertull** [comment]
Sounds great!

**Comment by patwater** [comment]
Beautiful!

**Comment by patwater** [comment]
Beautiful!  PS monobina you need a clever avatar photo :)

**Comment by monobina** [comment]
@patwater haha.. I'll have to find a good one :-)

**Comment by christophertull** [comment]
Closed by f8c0fed15420888db39c5acd87043c4f4f3e2315
